trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    sudo npm install -g @microsoft/rush
  displayName: 'Install Rush'

- script: |
    rush install --no-link
  displayName: 'rush install --no-link'

- script: |
    rush link
  displayName: 'rush link'
  
- script: |
    rush rebuild --ship --verbose
  displayName: 'rush rebuild --ship --verbose'
  
- script: |
    rush test --verbose
  displayName: 'rush test --verbose'
