trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    git submodule update --init --recursive
  displayName: 'setup git submodules'
  
- script: |
    yarn -v
    yarn
    yarn run build
  displayName: 'install packages and build all workspaces'
  
- script: |
    yarn run clean
  displayName: 'Check clean script'
