name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 11.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install alsa prereqs for midi module
      run:
        sudo apt-get install -y libasound2-dev
    - name: install rush
      run: |
        npm install -g @microsoft/rush
    - name: rush install
      run: |
        rush install
    - name: rush rebuild
      run: |
        rush rebuild
    - name: tslint
      run: |
        rush tslint
