name: Build & Publish Site

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install mono and msbuild (for docfx)
      run: |
        sudo apt install gnupg ca-certificates
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
        sudo apt update
        sudo apt install mono-devel
    - name: Download and prepare DocFX
      run: |
        sudo mkdir -p /opt/docfx/
        cd /opt/docfx
        sudo wget --quiet https://github.com/dotnet/docfx/releases/download/v2.48.1/docfx.zip -O /opt/docfx/docfx.zip
        sudo unzip qq docfx.zip
